"use client";
import Footer from "@/components/Footer";
import Navbar from "@/components/navbar/Navbar";
import Providers from "@/context/Providers";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <div className="dark:bg-dark1  bg-light2 font-poppins text-dark1  transition-all duration-700 dark:text-text1">
            <Navbar />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
